services:
  db:
    image: postgres:16-alpine
    container_name: pizzeria-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pizzeria
      POSTGRES_USER: pizzeria
      POSTGRES_PASSWORD: pizzeria
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - pizzeria-network

  app:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: pizzeria-app
    restart: unless-stopped
    environment:
      PORT: "3000"
      APP_ORIGIN: "http://localhost:3000,http://192.168.1.115:3000,https://meinfuhrer.share.zrok.io"
      SESSION_SECRET: "MEGUSTANlaspizzas1901070803"
      DATABASE_URL: "postgres://pizzeria:pizzeria@db:5432/pizzeria"
      ADMIN_USERNAME: "alex"
      ADMIN_EMAIL: "arodriguezarasil@gmail.com"
      ADMIN_PASSWORD: "Pizza12345"
      # OAuth / Firebase
      GOOGLE_CLIENT_ID: "292923743751-kt6l2p0npcba64f9irge2itrn5ps8k5m.apps.googleusercontent.com"
      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: 465
      SMTP_SECURE: true
      SMTP_USER: "arodriguezarasil@gmail.com"
      SMTP_PASS: "tftx uicd xfda pirm"
    depends_on:
      - db
    networks:
      - pizzeria-network

  zrok:
    image: openziti/zrok:latest
    container_name: pizzeria-zrok
    restart: unless-stopped
    user: "0:0"
    environment:
      HOME: /root
    command: >
      share reserved meinfuhrer --headless --override-endpoint http://app:3000
    depends_on:
      - app
    volumes:
      - ${HOME}/.zrok:/root/.zrok
    networks:
      - pizzeria-network

networks:
  pizzeria-network:
    external: true
    name: pizzeria-network

volumes:
  pgdata: